# String

s = "It means aa loop inside another loop, it is useful when we have multidimensional data like matrices   "
# print(s[1])
# print(s[1:10])
# print(s[10:])
# print(s[:10])
# print(s[:])
# print(s[-10])
# print(s[-10:])
s2 = "hello everyone"
# print(s+s2)

# print(s2.upper())
# print(s.lower())
# print(s2.capitalize())
# print(s.title())
# print(s.split())
# print(s.split('a'))
# s3 = s.split()
# print(s3)
# print(' hi '.join(s3))
# print(s.replace('a','was'))
# print(s)
# print(s.strip())
# print(s.lstrip())
# print(s.rstrip())

# print(s.find('is'))
# print(s.rfind('is'))
# print(s2.find('a'))
# print(s.rfind('a'))
# print(s.find('and'))
# print(s.index('and'))
# print(s.count('is'))
# print(s2.isalpha())
# print("2".isdigit())
# print("s2".isalnum())
# print(s2.isdecimal())
print(s2.startswith('i'))
print(s2.endswith('ig'))